<#
.SYNOPSIS
    Imports a Microsoft Intune configuration policy from JSON.

.DESCRIPTION
    Reads an exported Intune configuration policy, removes properties
    that should not be reused when creating a new policy, and submits
    the configuration to Microsoft Graph.

    The script is tenant-agnostic and uses the currently authenticated
    Microsoft Graph session.

.PARAMETER Path
    Path to the Intune policy JSON file.

.PARAMETER WhatIf
    Displays the prepared policy without submitting it to Microsoft Graph.

.EXAMPLE
    .\Import-IntuneConfiguration.ps1 -Path ".\ExamplePolicy.json" -WhatIf

.EXAMPLE
    .\Import-IntuneConfiguration.ps1 -Path ".\ExamplePolicy.json"

.NOTES
    Requires an existing Microsoft Graph connection with appropriate
    Intune write permissions.

    Microsoft Graph beta endpoints are used for configurationPolicies.
#>

[CmdletBinding(SupportsShouldProcess = $true)]
param(
    [Parameter(Mandatory = $true)]
    [ValidateScript({ Test-Path $_ -PathType Leaf })]
    [string]$Path
)

$ErrorActionPreference = "Stop"

try {

    if (-not (Get-Module -ListAvailable -Name Microsoft.Graph.Authentication)) {
        throw "Microsoft.Graph.Authentication is not installed."
    }

    Import-Module Microsoft.Graph.Authentication

    $Context = Get-MgContext

    if (-not $Context) {
        throw "No Microsoft Graph session detected. Authenticate with Connect-IntuneGraph.ps1 first."
    }

    Write-Host ""
    Write-Host "Reading Intune configuration..." -ForegroundColor Cyan

    $Policy = Get-Content -Path $Path -Raw |
        ConvertFrom-Json

    if (-not $Policy.name) {
        throw "The JSON file does not contain a policy name."
    }

    #
    # Remove properties generated by Intune that should not be
    # transferred to the new policy.
    #

    $PropertiesToRemove = @(
        "id",
        "createdDateTime",
        "lastModifiedDateTime",
        "settingCount",
        "isAssigned"
    )

    foreach ($Property in $PropertiesToRemove) {

        if ($Policy.PSObject.Properties.Name -contains $Property) {
            $Policy.PSObject.Properties.Remove($Property)
        }
    }

    $Body = $Policy |
        ConvertTo-Json -Depth 100

    Write-Host "Policy: $($Policy.name)"
    Write-Host "Tenant: $($Context.TenantId)"
    Write-Host ""

    if ($WhatIfPreference) {

        Write-Host "WHATIF - Policy would be submitted to Microsoft Graph." -ForegroundColor Yellow
        Write-Host ""
        Write-Output $Body
        return
    }

    $Uri = "https://graph.microsoft.com/beta/deviceManagement/configurationPolicies"

    if ($PSCmdlet.ShouldProcess(
        $Policy.name,
        "Create Intune configuration policy"
    )) {

        Write-Host "Importing policy..." -ForegroundColor Cyan

        $Response = Invoke-MgGraphRequest `
            -Method POST `
            -Uri $Uri `
            -Body $Body `
            -ContentType "application/json"

        Write-Host ""
        Write-Host "Import successful." -ForegroundColor Green
        Write-Host "Policy: $($Response.name)"
        Write-Host "ID:     $($Response.id)"
        Write-Host ""
    }
}
catch {

    Write-Error "Intune import failed: $($_.Exception.Message)"
}
